docs(cn): translate jest/docs/MoreResources.md
docschina/jest pull request #14
Opened 2020-08-17 02:40 UTC by KDcurryWang

2020-08-17 07:56 UTC, aladdin-add requested changes

2020-08-17 07:56 UTC, aladdin-add commented on docs/MoreResources.md
> +如果你想向其他的 Jest 使用者提问。 [Reactiflux](https://www.reactiflux.com/) 是一个有很多关于 Jest 的争论的社区。你可以阅读 `#testing` 标签下的消息。
争论 => 讨论
标签 => 频道

2020-08-17 08:57 UTC, KDcurryWang commented on docs/MoreResources.md
> +如果你想向其他的 Jest 使用者提问。 [Reactiflux](https://www.reactiflux.com/) 是一个有很多关于 Jest 的争论的社区。你可以阅读 `#testing` 标签下的消息。
感谢

2020-08-18 02:52 UTC, demopark requested changes
line 22:
争论 => 讨论
标签 => 频道

2020-08-18 02:52 UTC, demopark commented on docs/MoreResources.md
> +如果你想向其他的 Jest 使用者提问。 [Reactiflux](https://www.reactiflux.com/) 是一个有很多关于 Jest 的争论的社区。你可以阅读 `#testing` 标签下的消息。
> 争论 => 讨论
> 标签 => 频道

+1

2020-08-22 15:03 UTC, aladdin-add approved these changes
lgtm!

2020-08-24 06:03 UTC, demopark approved these changes

2020-10-09 09:52 UTC, lcxfs1991 approved these changes

2020-10-09 09:52 UTC, merged